### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by Sicks3c** [KathanP19/gaussrf#2] opened 2020-05-01 05:56 UTC
## Summary

Thank you for the awesome script <3
I have an issue while running the script see the image
![issueprivate](https://user-images.githubusercontent.com/32225186/80785467-e6eace00-8b6f-11ea-9361-b5f937aa39b3.JPG)

## Information

>Linux DESKTOP-75EI56B 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
> WSL 2

**Comment by KathanP19** [comment] 2020-05-01 16:52
the problem is with gau , reinstall gau it will be fixed 
`
https://github.com/lc/gau/issues?q=is%3Aissue+is%3Aclosed
`

**Closed as completed** 2020-05-01 16:54 UTC
